user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
# pid 放到 /tmp（overlay 文件系统），避免在 CentOS7 老内核的 tmpfs(/run) 上 pwrite 报 EPERM
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    include /etc/nginx/conf.d/*.conf;
}
